name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn install

      - name: Run tests and capture output
        id: test
        run: |
          mvn test | tee test-results.txt
          echo "DATE=$(date '+%d.%m.%Y %H:%M')" >> $GITHUB_ENV

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN  }}
          DATE: ${{ env.DATE }}
        run: |
          TEST_RESULTS=$(cat test-results.txt)
          gh release delete master -R ${{ github.repository }}
          gh release create master -R ${{ github.repository }} -t "Master $DATE" -n $'## Test Results\n```\n'"$TEST_RESULTS"
